<?xml version="1.0"?>
<package format="3">
  <name>manta_bringup</name>
  <version>0.0.0</version>
  <description>Launch and configuration package for the MantaClaus runtime stack.</description>
  <maintainer email="you@example.com">kushion</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>launch_xml</exec_depend>
  <exec_depend>brain</exec_depend>
  <exec_depend>cv</exec_depend>
  <exec_depend>ekfslam</exec_depend>
  <exec_depend>tasks</exec_depend>
  <exec_depend>mavros_control</exec_depend>
  <exec_depend>mavros</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
